server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer

  cloud:
    stream:
      binders: #在此处配置需要绑定的rabbitmq服务信息

        defaultRabbit: #表示定义的名称，用于binding的整合
          type: rabbit #消息组件类型
          enviroment: ##配置rabbitmq连接环境
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest

      bindings: #服务的整合处理
        input: #这个名字是一个通道的名字
          destination: studyExchange #表示要使用的Exchange名称定义
          content-type: application/json #设置消息类型，文本可以设置为：text/plain
          #binder: defaultRabbit #设置要要绑定的消息服务的具体设置

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔，默认30秒
    lease-expiration-duration-in-seconds: 5
    instance-id:  receive-8802.com #在消息列表显示主机名称
    prefer-ip-address: true #访问路径变为ip地址