server:
  port: 9527

spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh  #路由id,没有固定规则，要求唯一，建议配合服务名
         # uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
          predicates:
             - Path=/payment/get/** # 断言：路径相匹配的进行路由
        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
             - Path=/payment/lb/**
            # - After=2020-04-27T09:46:02.593+08:00[Asia/Shanghai]
            # - Cookie=username,z  # cmd:curl http://localhost:9527/payment/lb --cookie "username=z"
            #- Header=X-Request-Id,\d+ #请求头有X-Request-Id属性并且值为整数的正则表达式(curl http://localhost:9527/payment/lb -H "X-Request-Id:1111")
            # - Host=**.atguigu.com #curl http://localhost:9527/payment/lb -H "Host:www.atguigu.com"
            # - Method=GET
            # - Query=username,\d+ #要有参数名为username并且值为整数（curl http://localhost:9527/payment/lb?username=1）

eureka:
  instance:
    hostname: cloud-gate-service
  client: #服务提供者provider注册进eureka
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
